require("options")
require("keymaps")
require("plugins")
require("colorscheme")
require("lsp")
require("plugins-config/cmp")
require("plugins-config/comment")
require("plugins-config/fzf-lua")
require("plugins-config/lualine")
require("plugins-config/nvim-hlslens")
require("plugins-config/wilder-nvim")
require("plugins-config/nvim-tree-cfg")
require("plugins-config/markdown")
require("plugins-config/fterm")
require("plugins-config/rust")
vim.g.mapleader = " " -- Leader
